services:
  web:
    image: anomot/backend
    ports:
      - "8080:8080"
    links:
      - redis_db
      - db
    environment:
      - IS_LOCAL=true
      - SPRING_REDIS_URL=redis://redis-host:6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-host:5432/anomot
  db:
    hostname: db-host
    build:
      context: .
      dockerfile: pgDockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=anomot
      - POSTGRES_DB=anomot
  redis_db:
    hostname: redis-host
    image: redis
    ports:
      - "6379:6379"