services:
  server:
    build:
      context: nginx/
      dockerfile: Dockerfile
    image: anomot/nginx
    ports:
      - "443:443"
      - "80:80"
    environment:
      - CLIENT_DOMAIN=http://localhost:3000
      - NGINX_ENVSUBST_OUTPUT_DIR=etc/nginx
  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile
    image: anomot/backend
    ports:
      - "8080:8080"
    links:
      - redis_db
      - db
    environment:
      - IS_LOCAL=true
      - SPRING_REDIS_URL=redis://redis-host:6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-host:5432/anomot
      - MEDIA_SERVER_URL=media:5000
      - CLIENT_DOMAIN=
      - CONTACT_EMAIL=
      - CONTACT_MAIL=
      - EMAIL_HOST=
      - EMAIL_PASSWORD=
      - EMAIL_PORT=587
      - EMAIL_PROTOCOL=
      - EMAIL_USERNAME=
      - JWT_PRIVATE_KEY=
      - LOGO_URL=
      - IS_MAIN=true
    networks:
      - mediaservernet
      - default
  db:
    hostname: db-host
    build:
      context: .
      dockerfile: pgDockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=anomot
      - POSTGRES_DB=anomot
  redis_db:
    hostname: redis-host
    image: redis
    ports:
      - "6379:6379"
networks:
  mediaservernet:
    name: net
    external: true