package com.anomot.anomotbackend.dto

import com.anomot.anomotbackend.security.password.ValidPassword
import com.anomot.anomotbackend.utils.Constants
import org.jetbrains.annotations.NotNull
import javax.validation.constraints.NotEmpty
import javax.validation.constraints.Size

class PasswordResetDto(
        @NotNull
        @NotEmpty
        @Size(min = Constants.PASSWORD_RESET_CODE_LENGTH, max = Constants.PASSWORD_RESET_CODE_LENGTH)
        val code: String,
        @NotNull
        @NotEmpty
        // 36 is the size of UUIDs generated by the UUID class
        @Size(min = 36, max = 36)
        val identifier: String,
        @ValidPassword
        val newPassword: String
)
